import { Router, Request, Response } from 'express';
import { PrismaClient } from '@prisma/client';
import path from 'path';
import fs from 'fs';
import rateLimit from 'express-rate-limit';
import { upsertContact, sendEmail } from '../../services/ghl';
import { renderTemplate } from '../../services/email';

const prisma = new PrismaClient();
// Safely cast prisma for model extensions dynamically generated by Prisma CLI
const db = prisma as any;

export const newsletterRouter = Router();

// Public Rate Limiter: Max 10 newsletter subscriptions per IP per hour
const newsletterRateLimiter = rateLimit({
  windowMs: 60 * 60 * 1000,
  max: 10,
  statusCode: 429,
  standardHeaders: true,
  legacyHeaders: false,
  message: {
    error: 'Too many subscription attempts from this IP address. Please try again later.',
  },
  skip: (req) => {
    if (process.env.NODE_ENV === 'test' && !req.headers['x-forwarded-for'] && !req.headers['x-test-rate-limit']) {
      return true;
    }
    return false;
  },
  handler: (_req, res, _next, options) => {
    res.status(options.statusCode).json(options.message);
  },
});

export function validateNewsletterEmail(emailStr: string | undefined | null): { valid: boolean; error?: string; email?: string } {
  if (!emailStr || typeof emailStr !== 'string') {
    return { valid: false, error: 'Please enter your email address.' };
  }

  const trimmed = emailStr.trim().toLowerCase();
  if (!trimmed) {
    return { valid: false, error: 'Please enter your email address.' };
  }

  if (trimmed.length > 254) {
    return { valid: false, error: 'Email address cannot exceed 254 characters.' };
  }

  // RFC5322 compliant email regex check
  const emailRegex = /^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/;
  if (!emailRegex.test(trimmed)) {
    return { valid: false, error: 'Please enter a valid email address (e.g. founder@company.com).' };
  }

  return { valid: true, email: trimmed };
}

function getEmailUnsubscribeUrl(email: string): string {
  const apiBase = (process.env.API_URL || 'https://leadersperformance.ae').replace(/\/$/, '');
  return `${apiBase}/api/v1/newsletter/unsubscribe?email=${encodeURIComponent(email)}`;
}

function getEmailUnsubscribeHeaders(email: string): Record<string, string> {
  const oneClickUrl = getEmailUnsubscribeUrl(email);
  const mailtoUrl = `mailto:unsubscribe@leadersperformance.ae?subject=unsubscribe`;

  return {
    'List-Unsubscribe': `<${oneClickUrl}>, <${mailtoUrl}>`,
    'List-Unsubscribe-Post': 'List-Unsubscribe=One-Click',
  };
}

/**
 * Send welcome email to subscriber via GoHighLevel
 */
export async function sendNewsletterWelcomeEmail(email: string, contactId?: string): Promise<void> {
  const templatePath = path.join(__dirname, '../../../templates/welcome-newsletter.html');
  
  if (!fs.existsSync(templatePath)) {
    console.warn(`[Newsletter] Welcome email template not found at ${templatePath}`);
    return;
  }

  const rawTemplate = fs.readFileSync(templatePath, 'utf8');
  const unsubscribeUrl = getEmailUnsubscribeUrl(email);
  
  const html = renderTemplate(rawTemplate, {
    unsubscribe_url: unsubscribeUrl,
    email: email,
  });

  const subject = 'Welcome to The Founder Performance Newsletter';
  const emailHeaders = getEmailUnsubscribeHeaders(email);

  let targetContactId = contactId;

  if (!targetContactId) {
    targetContactId = await upsertContact({
      email,
      source: 'Leaders Performance Website Footer',
      tags: ['The Founder Performance Newsletter', 'Newsletter Subscriber'],
    });
  }

  if (targetContactId) {
    await sendEmail(targetContactId, subject, html, emailHeaders);
    console.log(`[Newsletter] Welcome email dispatched via GHL to contact ${targetContactId} (${email}) with RFC 8058 List-Unsubscribe headers`);
  }
}

/**
 * Send Issue #1 (Edition 01 - PDF) to subscriber via GoHighLevel
 */
export async function sendFirstNewsletterIssue(email: string, contactId?: string): Promise<void> {
  try {
    const templatePath = path.join(__dirname, '../../../templates/first-newsletter-issue.html');
    if (!fs.existsSync(templatePath)) {
      console.warn(`[Newsletter] Issue #1 template not found at ${templatePath}`);
      return;
    }

    // Check if already sent
    const sub = await db.newsletterSubscriber.findUnique({ where: { email } });
    if (sub && sub.firstIssueSent) {
      console.log(`[Newsletter] Issue #1 already sent to ${email}, skipping.`);
      return;
    }

    const rawTemplate = fs.readFileSync(templatePath, 'utf8');
    const unsubscribeUrl = getEmailUnsubscribeUrl(email);
    const baseUrl = (process.env.FRONTEND_URL || 'https://leadersperformance.ae').replace(/\/$/, '');
    const pdfUrl = `${baseUrl}/NEWSLETTER_DESKTOP_FINAL_REVISED.pdf`;

    const html = renderTemplate(rawTemplate, {
      unsubscribe_url: unsubscribeUrl,
      pdf_url: pdfUrl,
      email: email,
    });

    const subject = 'The Founder Performance Newsletter — Issue #1: Performance Under Pressure';
    const emailHeaders = getEmailUnsubscribeHeaders(email);

    let targetContactId = contactId || sub?.ghlContactId;

    if (!targetContactId) {
      targetContactId = await upsertContact({
        email,
        source: 'Leaders Performance Website Footer',
        tags: ['The Founder Performance Newsletter', 'Newsletter Subscriber', 'Issue #1 Sent'],
      });
    }

    if (targetContactId) {
      await sendEmail(targetContactId, subject, html, emailHeaders);
      console.log(`[Newsletter] Issue #1 (PDF Edition) dispatched via GHL to contact ${targetContactId} (${email}) with RFC 8058 headers`);

      await db.newsletterSubscriber.update({
        where: { email },
        data: {
          firstIssueSent: true,
          firstIssueSentAt: new Date(),
        },
      }).catch(() => null);
    }
  } catch (err) {
    console.error(`[Newsletter] Error sending Issue #1 to ${email}:`, err);
  }
}

/**
 * Async background handler to sync subscriber to GHL and send welcome email immediately.
 */
async function processBackgroundSubscription(email: string): Promise<void> {
  try {
    const ghlContactId = await upsertContact({
      email,
      source: 'Leaders Performance Website Footer',
      tags: ['The Founder Performance Newsletter', 'Newsletter Subscriber'],
    });

    if (ghlContactId) {
      await db.newsletterSubscriber.update({
        where: { email },
        data: { ghlContactId },
      }).catch(() => null);

      // Send Welcome Email immediately
      await sendNewsletterWelcomeEmail(email, ghlContactId);
    }
  } catch (err) {
    console.error('[Newsletter] Background processing error:', err);
  }
}

/**
 * @openapi
 * /newsletter/subscribe:
 *   post:
 *     summary: Subscribe to The Founder Performance Newsletter
 *     description: Validates email, adds contact to database & GHL newsletter list, dispatches welcome email immediately and sends Issue #1 1 minute later.
 *     tags:
 *       - Newsletter
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - email
 *             properties:
 *               email:
 *                 type: string
 *                 example: founder@company.com
 *     responses:
 *       200:
 *         description: Successfully subscribed or already subscribed
 *       400:
 *         description: Validation error
 *       500:
 *         description: Server error
 */
newsletterRouter.post('/subscribe', newsletterRateLimiter, async (req: Request, res: Response) => {
  try {
    const emailInput = req.body?.email;
    const validation = validateNewsletterEmail(emailInput);

    if (!validation.valid || !validation.email) {
      return res.status(400).json({ error: validation.error });
    }

    const email = validation.email;

    // 1. Check existing record in DB
    const existingSubscriber = await db.newsletterSubscriber.findUnique({
      where: { email },
    });

    if (existingSubscriber && existingSubscriber.status === 'subscribed') {
      return res.status(200).json({
        success: true,
        alreadySubscribed: true,
        message: 'This email address is already subscribed to The Founder Performance Newsletter.',
      });
    }

    // 2. Store / update in database
    if (existingSubscriber) {
      await db.newsletterSubscriber.update({
        where: { email },
        data: {
          status: 'subscribed',
          subscribedAt: new Date(),
        },
      });
    } else {
      await db.newsletterSubscriber.create({
        data: {
          email,
          status: 'subscribed',
          source: 'Website Footer',
        },
      });
    }

    // 3. Trigger async GHL sync, welcome email immediately, and 1-minute delayed Issue #1 dispatch
    processBackgroundSubscription(email);

    return res.status(200).json({
      success: true,
      alreadySubscribed: false,
      message: 'Thank you for subscribing to The Founder Performance Newsletter. A welcome email has been sent to your inbox.',
    });
  } catch (error) {
    console.error('[Newsletter] Error processing subscription:', error);
    return res.status(500).json({
      error: 'An unexpected error occurred while processing your subscription. Please try again.',
    });
  }
});

/**
 * Handle unsubscribe requests (both RFC 8058 One-Click HTTP POST and direct browser GET/POST)
 */
newsletterRouter.all(['/unsubscribe', '/newsletter/unsubscribe', '/api/newsletter/unsubscribe', '/api/v1/newsletter/unsubscribe'], async (req: Request, res: Response) => {
  try {
    const emailParam = req.query.email || req.body?.email || req.body?.ListUnsubscribe || req.body?.['List-Unsubscribe'];
    const validation = validateNewsletterEmail(String(emailParam || ''));

    if (!validation.valid || !validation.email) {
      if (req.method === 'GET' && req.headers.accept?.includes('text/html')) {
        return res.status(400).send(`
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Unsubscribe — Leaders Performance</title>
</head>
<body style="margin:0;padding:0;background:#051225;font-family:system-ui,-apple-system,sans-serif;color:#ffffff;display:flex;align-items:center;justify-content:center;min-height:100vh;padding:20px;box-sizing:border-box;">
  <div style="max-width:500px;width:100%;background:#081a35;border:1px solid rgba(215,185,120,0.3);border-radius:12px;padding:40px 32px;text-align:center;box-shadow:0 20px 40px rgba(0,0,0,0.5);">
    <h1 style="color:#ffffff;font-size:22px;margin-bottom:12px;">Unsubscribe Request</h1>
    <p style="color:#CECFD2;font-size:14px;margin-bottom:24px;">Please provide a valid email address to unsubscribe from the newsletter.</p>
    <a href="https://leadersperformance.ae" style="display:inline-block;background:#D7B978;color:#051225;padding:12px 24px;text-decoration:none;font-weight:600;border-radius:6px;">Return to Website</a>
  </div>
</body>
</html>
        `);
      }
      return res.status(400).json({ error: 'Please provide a valid email address to unsubscribe.' });
    }

    const email = validation.email;

    const existing = await db.newsletterSubscriber.findUnique({
      where: { email },
    });

    if (existing) {
      await db.newsletterSubscriber.update({
        where: { email },
        data: { status: 'unsubscribed' },
      });
    }

    // Update GHL tags in background
    upsertContact({
      email,
      tags: ['Unsubscribed - Founder Performance Newsletter'],
    }).catch((e) => console.warn('[Newsletter] Failed to update GHL unsubscribe tags:', e));

    console.log(`[Newsletter] Unsubscribe processed for ${email}`);

    // If browser navigation (clicking link in email body), render a beautiful HTML confirmation page directly!
    if (req.method === 'GET' && req.headers.accept?.includes('text/html')) {
      return res.status(200).send(`
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>You Have Been Unsubscribed — Leaders Performance</title>
</head>
<body style="margin:0;padding:0;background:#051225;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#ffffff;display:flex;align-items:center;justify-content:center;min-height:100vh;padding:20px;box-sizing:border-box;">
  <div style="max-width:540px;width:100%;background:#081a35;border:1px solid rgba(215,185,120,0.3);border-radius:12px;padding:44px 36px;text-align:center;box-shadow:0 20px 40px rgba(0,0,0,0.5);position:relative;">
    <div style="height:3px;width:100%;background:linear-gradient(90deg,transparent,#D7B978,transparent);position:absolute;top:0;left:0;border-radius:12px 12px 0 0;"></div>
    
    <div style="margin-bottom:24px;">
      <a href="https://leadersperformance.ae" target="_blank" style="display:inline-block;text-decoration:none;">
        <img src="https://leadersperformance.ae/assets/home/logo-gold.png" alt="Leaders Performance" width="150" style="display:block;margin:0 auto;width:150px;height:auto;border:0;" />
      </a>
    </div>

    <div style="display:inline-block;padding:4px 14px;background:rgba(215,185,120,0.12);border:1px solid rgba(215,185,120,0.3);border-radius:20px;font-size:11px;font-weight:600;letter-spacing:2px;color:#D7B978;text-transform:uppercase;margin-bottom:20px;">
      THE FOUNDER PERFORMANCE NEWSLETTER
    </div>

    <h1 style="font-family:Georgia,serif;font-size:26px;color:#ffffff;margin:0 0 14px 0;font-weight:600;">You Have Been Unsubscribed</h1>
    
    <p style="font-size:14px;line-height:1.6;color:#CECFD2;margin:0 0 28px 0;">
      Your email address <strong style="color:#D7B978;">${email}</strong> has been successfully unsubscribed from The Founder Performance Newsletter mailing list. You will no longer receive marketing communications or future issues.
    </p>

    <div>
      <a href="https://leadersperformance.ae" style="display:inline-block;background:#D7B978;color:#051225;padding:14px 28px;text-decoration:none;font-size:14px;font-weight:600;border-radius:6px;box-shadow:0 4px 12px rgba(215,185,120,0.2);">
        Return to Leaders Performance
      </a>
    </div>
  </div>
</body>
</html>
      `);
    }

    return res.status(200).json({
      success: true,
      message: 'You have been successfully unsubscribed from The Founder Performance Newsletter.',
    });
  } catch (error) {
    console.error('[Newsletter] Unsubscribe error:', error);
    return res.status(500).json({ error: 'Failed to process unsubscribe request.' });
  }
});
